[package]
name = "mazer-lisp"
version = "0.0.0"
edition = "2024"

[dependencies]
mazer-stdlib = { path = "../mazer-stdlib" }
mazer-types = { path = "../mazer-types" }
fastnum = "0.7.4"
unicode-segmentation = "1.12.0"
